import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300"],
  style: ["normal", "italic"], 
  display: "swap", 
});

export const metadata: Metadata = {
  title: "Suno - Modern Music Player – Add, Play, and Enjoy Your Own Songs",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.style} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
